<!-- Begin page content -->
<main role="main" class="container">

    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron bg-honeycomb">
        <div class="container">
            <h1 class="display-5 text-white text-center">Hi! Here's a bit more info about me...</h1>
            <p class="text-white">I have three of years experience working in support/systems admin, and software development. I enjoy solving problems, optimizing solutions, Oxford commas, and keeping detailed documentation. My goal is to leverage technology to provide the best service possible in support of the business. When I’m not coding or working, I still enjoy playing  trombone professionally.</p>
        </div>
    </div>



    <!-- Bio -->
    <div class="p-2 mb-5">
        <h2>Bio</h2>
        <hr>
        <p>I completed a Bachelors of Music degree at University of Toronto with honors and became a professional musician. In 2018 I decided to challenge myself, so I joined the Computer Programmer Analyst stream at George Brown College.</p>

        <p>While I attended George Brown, I worked for the college as an English Tutor and peer Tutor in the IT department which taught me good customer service skills. I found that the discipline and people skills that I learned as a musician served me well in this program and I graduated in 2021 with a 3.9 GPA.</p>

        <p> Since 2021 I have been working in IT, first as an IT Support Specialist before being promoted to Operations Support Specialist at an insurance company in Mississauga.</p>
    </div>


</main>