<main class="container">
    
    <!-- Education -->
    <div class="p-4 mb-5 mt-5">
            <h2>Education</h2>
            <hr>
            <div class="nav ml-5">
                <h5>Computer Programmer Analyst Advanced Diploma</h5>
                <strong class="ml-auto">September 2018 – April 2021</strong>
            </div>
            <i class="ml-5"><a href="https://www.georgebrown.ca/" target="_blank">George Brown College – Toronto, ON</a></i>
            <ul class="ml-5">
                <li>Dean's List</li>
                <li>Cumulative GPA: 3.9</li>
                <li>Created a solution in PHP using MVC design pattern to create retrieve, and update client information,
                create items associated with each client, and to manage user accounts with username and password. All data stored
                in SQL database, and validated on the server side.</li>
                <li>Created OOP solution in C# using windows forms GUI to take user input. The system created, retrieved, and
                updated information and implemented dependencies in the data to preserve integrity.</li>
                <li>Participated in Systems Analysis group project which covered the planning, analysis, and design phases of the SDLC,
                including diagrams and use-cases.</li>
            </ul>

            <!-- university -->
            <div class="nav ml-5">
                <h5>Bachelor of Music Performance</h5>
                <strong class="ml-auto">September 2008 – April 2012</strong>
            </div>
            <i class="ml-5"><a href="https://www.utoronto.ca/" target="_blank">University of Toronto – Toronto, ON</a></i>
            <ul class="ml-5">
                <li>Dean's List</li>
                <li>Graduated with honours</li>
            </ul>

        </div>

        <!-- Awards -->
        <div class="p-4 mb-5">
            <h2>Awards</h2>
            <hr>
            <ul>
                <li>Dean's List - George Brown College - Fall 2020</li>
                <li>Dean's List - George Brown College - Winter 2020</li>
                <li>Dean's List - George Brown College - Fall 2019</li>
                <li>Dean's List - George Brown College - Winter 2019</li>
                <li>Dean's List - George Brown College - Winter 2019</li>
                <li>Dean's List - George Brown College - Fall 2018</li>
            </ul>
        </div>

        <!-- Transcript -->
        <div class="p-4 mb-5 mt-5">
            <a class="btn btn-primary float-right" title="Download my Transcript" href="assets/Venables_Academic_Transcript.pdf">
                Download <i class="fas fa-file-download"></i></a>
            <h2>Transcript</h2>
            <hr>
        </div>



    <!-- Capstone Project -->
    <div class="p-4 mb-5">
            <h2>Capstone Project</h2>
            <hr>

            <h4>Project Summary and Vision</h4>
            <p>This app will provide a focused, streamlined, and yet flexible connection tool for new, introverted, or online-based
                students. The primary goal is to encourage connection and collaboration among fellow students specifically at the same
                college in a way that is more effective than the tools which currently exist.
                </p>
            <ul>
                <li>Focused</li>
                <ul>
                    <li>Users must belong to the same college - profile requires college email address.</li>
                    <li>Users provide profile information about their campus, program, semester, section, and classes - this enables
                        groups
                        formed to be focused at any of these levels</li>
                    <li>Can be used by teachers for class-specific group projects</li>
                </ul>
                <li>Streamlined</li>
                <ul>
                    <li>Once profile information is filled out, users can ideally create or join a well-matched group within a few clicks</li>
                </ul>
                <li>Flexible</li>
                <ul>
                    <li>Allows for creation of different kinds of groups, pulling from pool of colleagues with varying levels of specificity</li>
                </ul>
            </ul>

            <p>Once groups are formed, the app aims to provide methods to quickly share contact information, and connect through the
            collaboration channels of the group’s choice.</p>

            <p>It also aims to provide the additional functionality of feedback from user to user in terms their skills and
            personalities with the aim of improving suggested matches for future groups and helping users learn more about
            themselves
            </p>
            

            <div class="col-md-8  mb-3 mx-auto">
                <ul class="list-group">
                    <li class="list-group-item bg-dark text-white text-center">Documents</li>
                    <li class="list-group-item">
                        Project Vision
                        <a class="btn btn-primary float-right" title="Download" href="assets/capstone/T04_ProjectVision.pdf">
                            <i class="fas fa-file-download"></i></a>
                    </li>
                    <li class="list-group-item">
                        Project Requirements
                        <a class="btn btn-primary float-right" title="Download" href="assets/capstone/T04_RequirementsAnalysisDesign.pdf">
                            <i class="fas fa-file-download"></i></a>
                    </li>
                    <li class="list-group-item">
                        Project Plan
                        <a class="btn btn-primary float-right" title="Download" href="assets/capstone/T04_ProjectPlan.pdf">
                            <i class="fas fa-file-download"></i></a>
                    </li>
                    <li class="list-group-item">
                        Wireframes
                        <a class="btn btn-primary float-right" title="Download" href="assets/capstone/F20_T04_Figma_Mockup.pdf">
                            <i class="fas fa-file-download"></i></a>
                    </li>
                    <li class="list-group-item">
                        System Implementation
                        <a class="btn btn-primary float-right" title="Open Link" href="https://joina.group" target="_blank">
                            <i class="fas fa-external-link-alt"></i></a>
                    </li>
                </ul>
            </div>

        </div>
</main>