<div>
    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron mt-0 bg-honeycomb w-100 rounded-0">
        <div class="container">
            <h1 class="display-4 text-white text-center">Barrington Venables</h1>
            <p class="text-white text-center">IT professional, developer, musician</p>
        
            <div class="text-center">
                <a class="display-4 cust-link1" href="https://www.linkedin.com/in/barrven/" target="_blank" role="button"><span class="fab fa-linkedin"></span></a>
                <a class="display-4 cust-link1" href="https://github.com/barrven" target="_blank" role="button"><span class="fab fa-github-square"></a>
                <a class="display-4 cust-link1" href="mailto:barringtonvenables@gmail.com" target="_blank" role="button"><span class="fas fa-envelope"></a>
            </div>
        </div>
    </div>

    <!-- Begin page content -->
    <main role="main" class="container-fluid p-5">

        <div class="row mx-auto" style="max-width: 800px;">

            <div class="col-md card-link bg-light rounded m-2">
                <div class="m-2 pl-3">
                    <a href="?page=about" class="btn btn-outline-primary btn-lg float-right hover-special"><span class="fas fa-arrow-right"></span></a>
                    <h5>About Me</h5>
                    <ul>
                        <li>My story</li>
                        <li>Maybe I'll write a blog here, who knows!</li>
                    </ul>
                    
                </div>
                
            </div>
            <div class="col-md card-link rounded bg-light m-2">
                
                <div class="m-2 pl-3">
                    <a href="?page=projects" class="btn btn-outline-primary btn-lg float-right hover-special"><span class="fas fa-arrow-right"></span></a>
                    <h5>My Projects</h5>
                    <ul>
                        <li>Links to working demos and fun stuff I've played around with</li>
                        <li>Some video walk throughs and descriptions</li>
                    </ul>
                </div>
            </div>

        </div>

        <div class="row mx-auto" style="max-width: 800px;">

            <div class="col-md card-link rounded bg-light m-2">
                
                <div class="m-2 pl-3">
                    <a href="?page=cv" class="btn btn-outline-primary btn-lg float-right hover-special"><span class="fas fa-arrow-right"></span></a>
                    <h5>Resume / CV</h5>
                    <ul>
                        <li>Answers to all your questions about my work experience</li>
                        <li>A listing of every job I've ever done. Buckle up!</li>
                    </ul>
                </div>
            </div>
            <div class="col-md card-link rounded bg-light m-2">
 
                <div class="m-2 pl-3">
                    <a href="?page=academic" class="btn btn-outline-primary btn-lg float-right hover-special"><span class="fas fa-arrow-right"></span></a>
                    <h5>Academic</h5>
                    <ul>
                        <li>Education info</li>
                        <li>Courses and certifications</li>
                    </ul>
                </div>
            </div>
        </div>
        
    </main>
</div>