<main class="container">
    <h1>Infini Quiz</h1>
    <div id="inputGroup"></div>
</main>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    const data = <?php echo $response; ?>;
    console.log(data);

    renderInputGroup();

    function renderInputGroup(){
        if(!isValidData) return;
        
        $('#inputGroup').empty();
        const question = $('<h5>', { text: `${data.questionText}`});
        $('#inputGroup').append(question);
        
        // $('#inputGroup')

        data.options.forEach((item)=>{
            const label = $('<label>',{
                text: `(${item.id}) ${item.optionText} `
            });
            
            rdoInput = $('<input>', {
                type: 'radio',
                name: 'options',
                value: `${item.id}`
            });
            
            const br = $('<br>');

            label.append(rdoInput);
            $('#inputGroup').append(label, br);            
        });

        const btnAnswer = $('<button>', {
            text: 'Submit',
            click: ()=>{
                const selectedOption = document.querySelector('input[name="options"]:checked');
                console.log('guessed', selectedOption.value);

                let resultText = '';

                if(selectedOption.value == data.correct_answer) {
                    resultText = 'Correct!'
                    // todo: log result
                } else {
                    resultText = 'Incorrect.'
                }
                const pResult = $('<p>', {
                    text: resultText
                })

                const pExplanation = $('<p>', {
                    text: `${data.answerExplanationText}`
                })

                $('#inputGroup').append(pResult, pExplanation);
            }
        })
        $('#inputGroup').append(btnAnswer);
    }

    function isValidData(){
        if(isset(data.error)){
            console.log(data.error);
            const p = $('<p>', { class: 'error-msg', text: data.error});
            return false;
        }

        if(!isset(data.options)){
            return false;
        }

        return true;
    }
    
</script>
