<main class="container" id="main">
    <br>    
    <h1 class="">Infini Quiz</h1>
    <select id="courseSelect" onchange="dropDownChange(this, 'course')">
        <option value="">Select Course</option>
        <option value="comptia a+ core1">Comptia A+ Core 1</option>
        <option value="comptia a+ core2">Comptia A+ Core 2</option>
    </select>
    <div class="section-title">
        <h3 id="sectionTitle"></h3>
    </div>
    <ul id="sections"></ul>
</main>

<script>

    // add the local stylesheet
    $('<link>', {
        rel: 'stylesheet',
        type: 'text/css',
        href: 'style/localStyles/quiz.css' 
    }).appendTo('head');

    const cs = document.getElementById('courseSelect');
    const sections = document.getElementById('sections');

    //todo: populate dropdown with this info

    const courseList = <?php echo $courseListJson; ?>;
    // console.log('coursesData', courseList[0]);
    
    renderSections(courseList, 'course');


    // Set the dropdown value based on the URL parameter when the page loads
    document.addEventListener('DOMContentLoaded', () => {
        const urlParams = new URLSearchParams(window.location.search);
        const course = urlParams.get('course');
        if (course) cs.value = course;
    });

    function dropDownChange(e, filter) {
        const value = e.value;
        const url = new URL(window.location);

        // If there's already a 'rating' parameter, update it; otherwise, add it
        if (value) {
            url.searchParams.set(filter, value);
        } else {
            url.searchParams.delete(filter);
        }

        // Update the URL without reloading the page
        const newUrl = url.href;
        window.history.pushState({ path: newUrl }, '', newUrl);
        
        renderSections(courseList, 'course');
    }


    ////// Functions ////////////////////
    // note: jquery must be imported

    function renderSections(arr, filterName) {
        document.getElementById('sections').innerHTML = "";

        $('#sectionTitle').text('');

        const url = new URL(window.location.href);
        const params = new URLSearchParams(url.search);
        const filterStr = params.get(filterName);
        
        // Flatten the array of sections from the filtered items
        const sections = arr
        .filter((item) => filterStr === item.folder)
        .flatMap((item) => item.sections);

        if(sections.length !== 0){
            $('#sectionTitle').text('Sections');
        } else if (filterStr){
            $('#sectionTitle').text('No sections in this course');
        }
        // Loop through the flattened sections and attach each one
        sections.forEach((section) => {
            const itemElement = $('<li>', {
                class: 'section-item',
            });

            let sectionTitle = formatSectionTitle(section.title);

            const btnExpand = $('<button>', {
                class: 'section-button',
                click: () => { handleExpandClick(section, itemElement); },
                html: `
                    <span>${sectionTitle}</span>
                    <i class="fas fa-chevron-down"></i>`
            });
    
            itemElement.append(btnExpand);

            const divElement = $('<div>', {
                class: 'section-div',
                hidden: true,
            });

            attachSubSections(section, divElement);

            itemElement.append(divElement);

            $('#sections').append(itemElement);
        });

    }

    function handleButtonClick(item, e){
        // console.log('clicked', e);
    }

    function handleExpandClick(item, e){
        let element = e[0].querySelector('div');
        element.hidden = !element.hidden;
        e.hidden = !e.hidden;
    }

    function attachSubSections(item, e){
        
        item.subSections.forEach((ss) => {
            const p = $('<p>', {});
            
            const btn = $('<button>', {
                class: 'ss-button',
                click: () => { handleQuizClick(ss, formatSectionTitle(item.title)); },
                html: `
                <span>${ss}</span>
                <i class="fas fa-arrow-right"></i>
                `
            });

            p.append(btn);
            e.append(p);
        });
    }

    function handleQuizClick(title, section=''){
        
        const url = new URL(window.location);
        const params = new URLSearchParams(url.search);

        if (!params.get('course')) {
            alert('course must be selected before opening quiz');
            return;
        }

        url.searchParams.delete('page');
        url.searchParams.set('page', 'quizDetail');
        
        url.searchParams.set('section', section);
        url.searchParams.set('detail', title);

        window.open(url.href, '_blank');

    }

    function formatSectionTitle(str){
        return str.replace(/Book Chapter \d+ - /, '');
    }

</script>
