<main class="container">
    <h1 class="mb-2">Infini Quiz</h1>
    <div id="inputGroup"></div>
    <div id="btnGroup" class="mt-3">
        <button id="btnSubmit" class="btn btn-primary" onclick="handleSubmit()">Submit</button>
        <button class="btn btn-success" onclick="handleNextClick()">Next</button>
    </div>

</main>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    // add the local stylesheet
    $('<link>', {
        rel: 'stylesheet',
        type: 'text/css',
        href: 'style/localStyles/quiz.css' 
    }).appendTo('head');


    const data = <?php echo $response; ?>;
    // console.log(data);

    renderInputGroup();

    function renderInputGroup(){
        if(!isValidData) return;
        
        $('#inputGroup').empty();
        const question = $('<h5>', { 
            text: `${data.questionText}`,
            class: 'mt-3 mb-3'
        });
        $('#inputGroup').append(question);
        
        // $('#inputGroup')

        data.options.forEach((item)=>{
            const label = $('<label>',{
                text: `${item.id}. ${item.optionText} `,
                class: 'rdoInput-label'
            });
            
            rdoInput = $('<input>', {
                type: 'radio',
                name: 'options',
                value: `${item.id}`,
                hidden: true,
                change: ()=>{
                    console.log('hello');
                    let rs = document.querySelectorAll('input');
                    rs.forEach((i)=>{
                        if(i.checked){
                            i.parentElement.classList.add('rdoInput-label-selected');
                        } else {
                            i.parentElement.classList.remove('rdoInput-label-selected');
                        }

                    })
                }
            });
            
            const br = $('<br>');

            label.append(rdoInput);
            $('#inputGroup').append(label, br);            
        });

        // const btnAnswer = $('<button>', {
        //     text: 'Submit',
        //     click: ()=>{
        //         const selectedOption = document.querySelector('input[name="options"]:checked');
        //         console.log('guessed', selectedOption.value);

        //         let resultText = '';

        //         if(selectedOption.value == data.correct_answer) {
        //             resultText = 'Correct!'
        //             // todo: log result
        //         } else {
        //             resultText = 'Incorrect.'
        //         }
        //         const pResult = $('<p>', {
        //             text: resultText
        //         })

        //         const pExplanation = $('<p>', {
        //             text: `${data.answerExplanationText}`
        //         })

        //         $('#inputGroup').append(pResult, pExplanation);
        //     }
        // })
        // $('#inputGroup').append(btnAnswer);
    }

    function handleNextClick(){
        document.location.reload();
    }

    function handleSubmit(){
        const selectedOption = document.querySelector('input[name="options"]:checked');
        // console.log('guessed', selectedOption.value);

        const pResult = $('<p>', {
            class: 'result-text mt-3 text-center'
        });

        if(selectedOption.value == data.correct_answer) {
            pResult.text('Correct!')
            pResult.addClass('text-success');
            // todo: log result
        } else {
            pResult.text('Incorrect.')
            pResult.addClass('text-danger');
        }
        
        const pExplanation = $('<p>', {
            text: `${data.answerExplanationText}`,
            class: 'mt-3'
        })

        $('#inputGroup').append(pResult, pExplanation);
        $('#btnSubmit').hide();
    }

    function isValidData(){
        if(isset(data.error)){
            console.log(data.error);
            const p = $('<p>', { class: 'error-msg', text: data.error});
            return false;
        }

        if(!isset(data.options)){
            return false;
        }

        return true;
    }
    
</script>
