<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Barrington Venables personal website">
    <meta name="author" content="Barrington Venables">
    
    <title>Venabar <?php echo ucfirst($page); ?></title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css">

    <!-- Icons -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.2/css/all.css">

    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="style/sticky-footer-navbar.css">
    <link rel="stylesheet" href="style/main.css">
    <link rel="icon" href="assets/favicon.ico">
</head>

<body>

    <!-- navbar -->
    <?php
        // these pages should have no navbar
        $noNavbar = ['home', 'test'];
        if(!in_array($page, $noNavbar)){
            include 'navbar.phtml';
        }
    ?>
    
    <!-- page content here. for it to bahave properly, wrap in a <main> element-->
    <div>
        <?php include $view; ?>
    </div>

    <!-- footer (obviously) -->
    <footer class="footer bg-dark text-white">
        <div class="container text-center">
            &copy; <?php echo date('Y'); ?> Barrington Venables
        </div>
    </footer>
    
    <script src="js/combine-hover.js"></script>
    <!-- jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"></script>

</body>

</html>