<!-- Fixed navbar -->
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
        aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="nav-item">
        <a class="nav-link" href="?page=home" title="home">
            <!-- <span class="fas fa-home fa-lg"></span> -->
            <img style="width: 2.5em;" src="assets/bslogo.png">
            <!-- <span>Home</span> -->
        </a>
    </div>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
            

            <li class="nav-item <?php echo $page == 'about'? 'active' : ''; ?>">
                <a class="nav-link" href="?page=about">About Me</a>
            </li>

            <li class="nav-item <?php echo $page == 'projects'? 'active' : ''; ?>">
                <a class="nav-link" href="?page=projects">My Projects</a>
            </li>

            <li class="nav-item <?php echo $page == 'cv'? 'active' : ''; ?>">
                <a class="nav-link" href="?page=cv">Resume / CV</a>
            </li>

            <li class="nav-item <?php echo $page == 'academic'? 'active' : ''; ?>">
                <a class="nav-link" href="?page=academic">Academic</a>
            </li>
        </ul>
    </div>
</nav>
<br>